//! Layer 8: cross-check our geometry against the real Vega-Lite.
//!
//! Reference scenegraphs are generated by `tests/vega-ref/dump.mjs` and committed
//! as `<fixture>.vega.json`. Regenerate with:
//!
//! ```text
//! cd tests/vega-ref && npm install && node dump.mjs
//! ```
//!
//! **What is and is not compared.** Vega running in Node has no canvas, so it
//! cannot call `measureText` and falls back to a crude width estimate. Its
//! absolute coordinates are therefore not a usable reference — the plot origin
//! moves with how wide it guesses the y tick labels are. Both sides are
//! normalised to the plot rectangle, which cancels that out and leaves the thing
//! worth checking: whether our scales agree with Vega's.
//!
//! For the same reason, positions that depend on measured text width (the y-axis
//! title, principally) are deliberately out of scope here. Layer 10's pixel
//! comparison covers those, in a browser, with a real canvas.

mod common;

use std::collections::BTreeSet;
use std::path::Path;

use chart_renderer::ir::SceneItem;
use chart_renderer::render_scene;
use serde_json::Value;

use common::{fixtures_dir, fixture_names, read_fixture};

/// Vega nudges axis labels by half a pixel for crisp rendering; ticks and marks
/// are not nudged. Anything within this is agreement.
const TOLERANCE: f32 = 0.02;
const LABEL_TOLERANCE: f32 = 0.75;

fn reference(name: &str) -> Option<Value> {
    let path = fixtures_dir().join(format!("{name}.vega.json"));
    let text = std::fs::read_to_string(&path).ok()?;
    serde_json::from_str(&text).ok()
}

fn role<'a>(reference: &'a Value, role: &str) -> Vec<&'a Value> {
    reference
        .get("marks")
        .and_then(|m| m.get(role))
        .and_then(|v| v.as_array())
        .map(|a| a.iter().collect())
        .unwrap_or_default()
}

fn num(item: &Value, key: &str) -> Option<f32> {
    item.get(key)?.as_f64().map(|v| v as f32)
}

/// Data marks only.
///
/// A legend draws swatches and labels with the same item kinds the plot does, so
/// every comparison here has to be scoped to the plot rectangle or it ends up
/// comparing Vega's bars against our legend.
fn in_plot(scene: &chart_renderer::ir::Scene, x: f32, y: f32) -> bool {
    x <= scene.plot.x + scene.plot.w + 1e-3 && y >= scene.plot.y - 1e-3
}

/// Guards against the reference files silently going missing, which would turn
/// every comparison below into a vacuous pass.
#[test]
fn reference_scenegraphs_are_present() {
    let missing: Vec<String> = fixture_names()
        .into_iter()
        .filter(|n| !Path::new(&fixtures_dir().join(format!("{n}.vega.json"))).exists())
        .collect();
    assert!(
        missing.is_empty(),
        "missing reference scenegraphs for {missing:?} — run `cd tests/vega-ref && node dump.mjs`"
    );
}

#[test]
fn plot_dimensions_match_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let scene = render_scene(&read_fixture(&name)).unwrap();
        let want_w = num(&reference["plot"], "width").unwrap();
        let want_h = num(&reference["plot"], "height").unwrap();
        assert!(
            (scene.plot.w - want_w).abs() < TOLERANCE && (scene.plot.h - want_h).abs() < TOLERANCE,
            "{name}: plot {}x{}, vega says {want_w}x{want_h}",
            scene.plot.w,
            scene.plot.h
        );
    }
}

#[test]
fn bar_geometry_matches_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let scene = render_scene(&read_fixture(&name)).unwrap();

        let ours: Vec<(f32, f32, f32, f32)> = scene
            .items
            .iter()
            .filter_map(|i| match i {
                SceneItem::Rect { x, y, w, h, .. } if in_plot(&scene, x + w, *y) => {
                    Some((x - scene.plot.x, y - scene.plot.y, *w, *h))
                }
                _ => None,
            })
            .collect();

        let theirs: Vec<(f32, f32, f32, f32)> = role(&reference, "mark")
            .iter()
            .filter_map(|it| {
                Some((
                    num(it, "x")?,
                    num(it, "y")?,
                    num(it, "width")?,
                    num(it, "height")?,
                ))
            })
            .collect();

        assert_eq!(
            ours.len(),
            theirs.len(),
            "{name}: we drew {} bars, vega drew {}",
            ours.len(),
            theirs.len()
        );

        for (i, (a, b)) in ours.iter().zip(&theirs).enumerate() {
            let d = (
                (a.0 - b.0).abs(),
                (a.1 - b.1).abs(),
                (a.2 - b.2).abs(),
                (a.3 - b.3).abs(),
            );
            assert!(
                d.0 < TOLERANCE && d.1 < TOLERANCE && d.2 < TOLERANCE && d.3 < TOLERANCE,
                "{name} bar {i}: ours {a:?}, vega {b:?}"
            );
        }
    }
}

#[test]
fn arc_geometry_matches_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let theirs: Vec<(f32, f32, f32, f32)> = role(&reference, "mark")
            .iter()
            .filter_map(|it| {
                Some((
                    num(it, "angle0")?,
                    num(it, "angle1")?,
                    num(it, "outerRadius")?,
                    num(it, "innerRadius").unwrap_or(0.0),
                ))
            })
            .collect();
        if theirs.is_empty() {
            continue;
        }

        let scene = render_scene(&read_fixture(&name)).unwrap();
        let ours: Vec<(f32, f32, f32, f32)> = scene
            .items
            .iter()
            .filter_map(|i| match i {
                SceneItem::Arc {
                    start_angle,
                    end_angle,
                    outer_radius,
                    inner_radius,
                    ..
                } => Some((
                    start_angle.min(*end_angle),
                    start_angle.max(*end_angle),
                    *outer_radius,
                    *inner_radius,
                )),
                _ => None,
            })
            .collect();

        assert_eq!(
            ours.len(),
            theirs.len(),
            "{name}: we drew {} slices, vega drew {}",
            ours.len(),
            theirs.len()
        );

        // Both sides emit in data order, so slice i is the same datum on each.
        // The angles are what encode the stacking order, and getting that wrong
        // silently rearranges the chart.
        for (i, (a, b)) in ours.iter().zip(&theirs).enumerate() {
            assert!(
                (a.0 - b.0).abs() < TOLERANCE
                    && (a.1 - b.1).abs() < TOLERANCE
                    && (a.2 - b.2).abs() < TOLERANCE
                    && (a.3 - b.3).abs() < TOLERANCE,
                "{name} slice {i}: ours {a:?}, vega {b:?}"
            );
        }
    }
}

/// The pie's centre, which the angle comparison above cannot see.
#[test]
fn arc_centres_match_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let theirs: Vec<(f32, f32)> = role(&reference, "mark")
            .iter()
            .filter(|it| it.get("angle0").is_some())
            .filter_map(|it| Some((num(it, "x")?, num(it, "y")?)))
            .collect();
        if theirs.is_empty() {
            continue;
        }

        let scene = render_scene(&read_fixture(&name)).unwrap();
        let ours: Vec<(f32, f32)> = scene
            .items
            .iter()
            .filter_map(|i| match i {
                SceneItem::Arc { cx, cy, .. } => {
                    Some((cx - scene.plot.x, cy - scene.plot.y))
                }
                _ => None,
            })
            .collect();

        for (i, (a, b)) in ours.iter().zip(&theirs).enumerate() {
            assert!(
                (a.0 - b.0).abs() < TOLERANCE && (a.1 - b.1).abs() < TOLERANCE,
                "{name} slice {i}: centre {a:?}, vega {b:?}"
            );
        }
    }
}

#[test]
fn gridline_positions_match_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let scene = render_scene(&read_fixture(&name)).unwrap();

        // Our gridlines span the full plot; take the constant coordinate of each.
        let ours: Vec<f32> = scene
            .items
            .iter()
            .filter_map(|i| match i {
                SceneItem::Line { points, stroke } if points.len() == 2 => {
                    // Gridlines are the light-grey ones.
                    if stroke.color != chart_renderer::ir::Color::rgb(0xdd, 0xdd, 0xdd) {
                        return None;
                    }
                    let (a, b) = (points[0], points[1]);
                    Some(if (a.1 - b.1).abs() < TOLERANCE {
                        a.1 - scene.plot.y
                    } else {
                        a.0 - scene.plot.x
                    })
                }
                _ => None,
            })
            .collect();

        let theirs: Vec<f32> = role(&reference, "axis-grid")
            .iter()
            .filter_map(|it| {
                // A horizontal gridline varies in x and holds y; vice versa.
                if it.get("x2").is_some() {
                    num(it, "y")
                } else {
                    num(it, "x")
                }
            })
            .collect();

        let sorted = |mut v: Vec<f32>| {
            v.sort_by(|a, b| a.partial_cmp(b).unwrap());
            v
        };
        let (ours, theirs) = (sorted(ours), sorted(theirs));

        assert_eq!(
            ours.len(),
            theirs.len(),
            "{name}: {} gridlines, vega has {}",
            ours.len(),
            theirs.len()
        );
        for (a, b) in ours.iter().zip(&theirs) {
            assert!(
                (a - b).abs() < TOLERANCE,
                "{name}: gridline at {a}, vega at {b} (all ours {ours:?}, vega {theirs:?})"
            );
        }
    }
}

#[test]
fn tick_labels_match_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let scene = render_scene(&read_fixture(&name)).unwrap();

        let titles: BTreeSet<String> = role(&reference, "axis-title")
            .iter()
            .filter_map(|it| it.get("text")?.as_str().map(String::from))
            .collect();

        let ours: BTreeSet<String> = scene
            .items
            .iter()
            .filter_map(|i| match i {
                // Legend text sits to the right of the plot; axis labels do not.
                SceneItem::Text { content, x, y, .. } if in_plot(&scene, *x, *y) => {
                    Some(content.clone())
                }
                _ => None,
            })
            .filter(|t| !titles.contains(t))
            .collect();

        let theirs: BTreeSet<String> = role(&reference, "axis-label")
            .iter()
            .filter_map(|it| it.get("text")?.as_str().map(String::from))
            .collect();

        assert_eq!(ours, theirs, "{name}: tick label sets differ");
    }
}

#[test]
fn category_label_positions_match_vega() {
    for name in fixture_names() {
        let Some(reference) = reference(&name) else {
            continue;
        };
        let scene = render_scene(&read_fixture(&name)).unwrap();

        // Compare only the bottom axis labels, whose placement does not depend on
        // measured text width — their anchor is the centre of the band.
        let theirs: Vec<(String, f32)> = role(&reference, "axis-label")
            .iter()
            .filter_map(|it| {
                let text = it.get("text")?.as_str()?.to_string();
                // Vega's axis items are positioned within their own axis group.
                // A left-axis label is pushed out to a negative x (-7 by default,
                // being tickSize + labelPadding); a bottom-axis label never is.
                // That, not the y coordinate, is what separates the two axes.
                let x = num(it, "x")?;
                (x > -1.0).then_some((text, x))
            })
            .collect();

        for (text, want_x) in theirs {
            // Look only at our bottom-axis labels: the same text can appear on
            // both axes (a scatter has a "0" on each), and matching by content
            // alone would compare the wrong one.
            let found = scene.items.iter().find_map(|i| match i {
                SceneItem::Text { content, x, y, .. }
                    if *content == text && *y > scene.plot.y + scene.plot.h =>
                {
                    Some(x - scene.plot.x)
                }
                _ => None,
            });
            let Some(got_x) = found else {
                panic!("{name}: vega drew label {text:?} and we did not");
            };
            assert!(
                (got_x - want_x).abs() < LABEL_TOLERANCE,
                "{name}: label {text:?} at {got_x}, vega at {want_x}"
            );
        }
    }
}
