// Generated by `npm run sync-wasm` — do not edit.
//
// These are the crate's own test fixtures, copied in verbatim, so the gallery
// and the test suite cannot drift apart.

export interface Sample {
  name: string
  description: string
  spec: unknown
}

export const SAMPLES: Sample[] = [
  {
    name: "colored_bar",
    description: "Bars coloured by a second nominal field. Categories are deliberately unsorted in the data, since Vega sorts nominal domains.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "Bars coloured by a second nominal field. Categories are deliberately unsorted in the data, since Vega sorts nominal domains.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "site": "Zeta",
            "yield": 31,
            "region": "west"
          },
          {
            "site": "Alpha",
            "yield": 48,
            "region": "east"
          },
          {
            "site": "Mid",
            "yield": 22,
            "region": "west"
          },
          {
            "site": "Beta",
            "yield": 56,
            "region": "east"
          }
        ]
      },
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "site",
          "type": "nominal"
        },
        "y": {
          "field": "yield",
          "type": "quantitative"
        },
        "color": {
          "field": "region",
          "type": "nominal"
        }
      }
    },
  },
  {
    name: "donut",
    description: "A donut — the same arc mark with an inner radius punched out.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "A donut — the same arc mark with an inner radius punched out.",
      "width": 260,
      "height": 260,
      "data": {
        "values": [
          {
            "browser": "Chrome",
            "share": 64
          },
          {
            "browser": "Safari",
            "share": 19
          },
          {
            "browser": "Edge",
            "share": 5
          },
          {
            "browser": "Firefox",
            "share": 3
          },
          {
            "browser": "Other",
            "share": 9
          }
        ]
      },
      "mark": {
        "type": "arc",
        "innerRadius": 60
      },
      "encoding": {
        "theta": {
          "field": "share",
          "type": "quantitative"
        },
        "color": {
          "field": "browser",
          "type": "nominal"
        }
      }
    },
  },
  {
    name: "empty_data",
    description: "No rows at all. Must render an empty chart, not fail.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "No rows at all. Must render an empty chart, not fail.",
      "width": 200,
      "height": 150,
      "data": {
        "values": []
      },
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "category",
          "type": "nominal"
        },
        "y": {
          "field": "amount",
          "type": "quantitative"
        }
      }
    },
  },
  {
    name: "horizontal_bar",
    description: "The same data with the discrete channel on y, giving horizontal bars.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "The same data with the discrete channel on y, giving horizontal bars.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "category": "A",
            "amount": 28
          },
          {
            "category": "B",
            "amount": 55
          },
          {
            "category": "C",
            "amount": 43
          },
          {
            "category": "D",
            "amount": 91
          }
        ]
      },
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "amount",
          "type": "quantitative"
        },
        "y": {
          "field": "category",
          "type": "nominal"
        }
      }
    },
  },
  {
    name: "line",
    description: "A single line over a quantitative x axis, with rows deliberately out of order.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "A single line over a quantitative x axis, with rows deliberately out of order.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "step": 3,
            "value": 28
          },
          {
            "step": 1,
            "value": 12
          },
          {
            "step": 5,
            "value": 43
          },
          {
            "step": 2,
            "value": 35
          },
          {
            "step": 4,
            "value": 22
          }
        ]
      },
      "mark": "line",
      "encoding": {
        "x": {
          "field": "step",
          "type": "quantitative"
        },
        "y": {
          "field": "value",
          "type": "quantitative"
        }
      }
    },
  },
  {
    name: "line_discrete_x",
    description: "A line over a discrete x axis, which uses a point scale rather than a band scale.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "A line over a discrete x axis, which uses a point scale rather than a band scale.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "month": "Jan",
            "sales": 18
          },
          {
            "month": "Feb",
            "sales": 25
          },
          {
            "month": "Mar",
            "sales": 14
          },
          {
            "month": "Apr",
            "sales": 33
          }
        ]
      },
      "mark": "line",
      "encoding": {
        "x": {
          "field": "month",
          "type": "nominal"
        },
        "y": {
          "field": "sales",
          "type": "quantitative"
        }
      }
    },
  },
  {
    name: "multi_series_line",
    description: "A colour encoding splits the data into one line per series, with a legend.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "A colour encoding splits the data into one line per series, with a legend.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "step": 1,
            "value": 10,
            "series": "north"
          },
          {
            "step": 2,
            "value": 18,
            "series": "north"
          },
          {
            "step": 3,
            "value": 15,
            "series": "north"
          },
          {
            "step": 4,
            "value": 27,
            "series": "north"
          },
          {
            "step": 1,
            "value": 22,
            "series": "south"
          },
          {
            "step": 2,
            "value": 14,
            "series": "south"
          },
          {
            "step": 3,
            "value": 31,
            "series": "south"
          },
          {
            "step": 4,
            "value": 20,
            "series": "south"
          }
        ]
      },
      "mark": "line",
      "encoding": {
        "x": {
          "field": "step",
          "type": "quantitative"
        },
        "y": {
          "field": "value",
          "type": "quantitative"
        },
        "color": {
          "field": "series",
          "type": "nominal"
        }
      }
    },
  },
  {
    name: "negative_bar",
    description: "Values straddling zero, so bars extend both ways from a shared baseline.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "Values straddling zero, so bars extend both ways from a shared baseline.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "quarter": "Q1",
            "delta": 14
          },
          {
            "quarter": "Q2",
            "delta": -22
          },
          {
            "quarter": "Q3",
            "delta": 7
          },
          {
            "quarter": "Q4",
            "delta": -3
          }
        ]
      },
      "mark": {
        "type": "bar",
        "color": "#e45756"
      },
      "encoding": {
        "x": {
          "field": "quarter",
          "type": "nominal"
        },
        "y": {
          "field": "delta",
          "type": "quantitative"
        }
      }
    },
  },
  {
    name: "pie",
    description: "A pie chart. Categories are unsorted in the data, since Vega stacks slices in colour-domain order rather than row order.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "A pie chart. Categories are unsorted in the data, since Vega stacks slices in colour-domain order rather than row order.",
      "data": {
        "values": [
          {
            "category": "Zeta",
            "value": 10
          },
          {
            "category": "Alpha",
            "value": 20
          },
          {
            "category": "Mid",
            "value": 5
          },
          {
            "category": "Beta",
            "value": 12
          }
        ]
      },
      "mark": "arc",
      "encoding": {
        "theta": {
          "field": "value",
          "type": "quantitative"
        },
        "color": {
          "field": "category",
          "type": "nominal"
        }
      }
    },
  },
  {
    name: "scatter",
    description: "Point marks on two quantitative scales.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "Point marks on two quantitative scales.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "weight": 3,
            "score": 28
          },
          {
            "weight": 7,
            "score": 55
          },
          {
            "weight": 12,
            "score": 43
          },
          {
            "weight": 18,
            "score": 91
          },
          {
            "weight": 21,
            "score": 66
          }
        ]
      },
      "mark": "point",
      "encoding": {
        "x": {
          "field": "weight",
          "type": "quantitative"
        },
        "y": {
          "field": "score",
          "type": "quantitative"
        }
      }
    },
  },
  {
    name: "simple_bar",
    description: "A basic bar chart with a nominal x axis.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "A basic bar chart with a nominal x axis.",
      "width": 300,
      "height": 200,
      "data": {
        "values": [
          {
            "category": "A",
            "amount": 28
          },
          {
            "category": "B",
            "amount": 55
          },
          {
            "category": "C",
            "amount": 43
          },
          {
            "category": "D",
            "amount": 91
          },
          {
            "category": "E",
            "amount": 81
          },
          {
            "category": "F",
            "amount": 53
          }
        ]
      },
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "category",
          "type": "nominal"
        },
        "y": {
          "field": "amount",
          "type": "quantitative"
        }
      }
    },
  },
  {
    name: "single_datum",
    description: "One row, which gives the quantitative scale a zero-width data extent.",
    spec: {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "description": "One row, which gives the quantitative scale a zero-width data extent.",
      "width": 200,
      "height": 150,
      "data": {
        "values": [
          {
            "category": "only",
            "amount": 42
          }
        ]
      },
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "category",
          "type": "nominal"
        },
        "y": {
          "field": "amount",
          "type": "quantitative"
        }
      }
    },
  },
]
