// Refreshes everything this demo vendors from the chart-renderer crate.
//
//   npm run sync-wasm
//
// Run it after changing the library. The demo deliberately consumes committed
// build artefacts rather than shelling out to cargo, so that a Cloudflare Pages
// build needs no Rust toolchain — the cost of that is this script.

import { execSync } from 'child_process';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const crate = join(here, '../lib');
const pkg = join(crate, 'crates/wasm/pkg');

console.log('Building the wasm package...');
execSync('wasm-pack build --release --target web --out-dir pkg', {
  cwd: join(crate, 'crates/wasm'),
  stdio: 'inherit',
});

console.log('Vendoring into the demo...');
const vendor = join(here, 'vendor/chart-renderer');
rmSync(vendor, { recursive: true, force: true });
mkdirSync(vendor, { recursive: true });
cpSync(pkg, vendor, { recursive: true });
// wasm-pack drops a .gitignore that would exclude the very files we vendor.
rmSync(join(vendor, '.gitignore'), { force: true });

console.log('Copying the embedded font...');
// The reference pane must render with the *same* font the library embeds, or the
// side-by-side comparison is measuring font differences rather than layout ones.
cpSync(
  join(crate, 'crates/core/assets/LiberationSans-Subset.ttf'),
  join(here, 'src/LiberationSans-Subset.ttf')
);

console.log('Regenerating samples from the crate fixtures...');
const fixturesDir = join(crate, 'crates/core/tests/fixtures');
const samples = readdirSync(fixturesDir)
  .filter((f) => f.endsWith('.json') && !f.endsWith('.vega.json'))
  .sort()
  .map((f) => {
    const spec = JSON.parse(readFileSync(join(fixturesDir, f), 'utf8'));
    const body = JSON.stringify(spec, null, 2)
      .split('\n')
      .map((line, i) => (i === 0 ? line : '    ' + line))
      .join('\n');
    return `  {
    name: ${JSON.stringify(f.replace(/\.json$/, ''))},
    description: ${JSON.stringify(spec.description ?? '')},
    spec: ${body},
  },`;
  });

writeFileSync(
  join(here, 'src/samples.ts'),
  `// Generated by \`npm run sync-wasm\` — do not edit.
//
// These are the crate's own test fixtures, copied in verbatim, so the gallery
// and the test suite cannot drift apart.

export interface Sample {
  name: string
  description: string
  spec: unknown
}

export const SAMPLES: Sample[] = [
${samples.join('\n')}
]
`
);

if (!existsSync(join(vendor, 'chart_renderer_wasm_bg.wasm'))) {
  console.error('wasm missing after sync — something went wrong');
  process.exit(1);
}
console.log(`Done. ${samples.length} samples.`);
